// All site content lives here. Edit values, refresh page. No build step.

// Attribute chart. value = 0-100, shape only (not shown). can = what I can do in this field.
window.STATS = [
  { key: "Product", value: 92, can: "ตีโจทย์ให้ชัด วาง MVP และพาทีมส่งงานจนจบ" },
  { key: "AI", value: 88, can: "มี Wiki และ Skill ของตัวเอง ใช้ Token คุ้ม เซฟงานทุกขั้น AI รู้บริบทเองโดยไม่ต้องเล่าซ้ำ" },
  { key: "Clutch", value: 90, can: "ส่งงานได้ใต้เวลาบีบ เช่น Hackathon 12 ชม. หรือเตรียม CTF 7 วัน" },
  { key: "Pitch", value: 85, can: "เล่าโปรเจกต์ให้เข้าใจง่าย และตอบคำถามกรรมการได้ตรงจุด" },
  { key: "Teamwork", value: 88, can: "แบ่งงานตามความถนัด และพาทีมไปทางเดียวกัน" },
  { key: "Web", value: 72, can: "ทำเว็บตั้งแต่หน้าบ้านถึงหลังบ้าน ส่งลูกค้าจริงได้" },
  { key: "Systems", value: 62, can: "ต่อหลายระบบให้คุยกันได้ เช่น PC กับมือถือผ่านสาย USB" },
  { key: "Security", value: 65, can: "สืบข้อมูล OSINT และแกะโปรแกรมหาจุดอ่อนได้" },
  { key: "Game Dev", value: 30, can: "ทำเกมเล่นได้จริงใน 3 วัน ยังฝึกอยู่" },
];

// Skill tree. lv = 1-10. max: true shows "MAX". can = what this level actually did.
window.SKILLS = [
  { group: "Product & Team", items: [
    { name: "Product Management", lv: 8, can: "คุมทีม *3–6 คน*ให้โฟกัสและส่งงานจนจบโดยไม่หมดไฟ" },
    { name: "MVP Scoping", lv: 9, can: "ตัดไอเดียให้เหลือ MVP ที่เดโมได้ภายใน *12 ชม.*" },
    { name: "Pitching / ตอบกรรมการ", lv: 8, can: "เล่าโปรเจกต์ให้เข้าใจง่าย และตอบคำถามกรรมการได้ตรงจุด" },
  ]},
  { group: "AI Tools", items: [
    { name: "Claude / Claude Code", lv: 9, can: "สร้าง Wiki และ Skill ของตัวเอง ให้ AI เข้าใจบริบทงานโดยไม่ต้องเล่าซ้ำ" },
    { name: "Codex", lv: 8, can: "ใช้ Token อย่างคุ้มค่า และเซฟความคืบหน้างานได้ทุกขั้น" },
    { name: "AI Model Integration", lv: 5, can: "ต่อโมเดล AI ขึ้น Server ให้แอปเรียกใช้ผ่าน API ได้" },
  ]},
  { group: "Web & Backend", items: [
    { name: "React + TypeScript", lv: 6, can: "ทำเว็บที่ล็อกอินด้วย Google และดึงข้อมูลจาก API มาแสดงได้" },
    { name: "Next.js", lv: 6, can: "ทำเว็บพร้อม SEO ส่งให้*ลูกค้าจริง*ใช้งานได้" },
    { name: "FastAPI / Python", lv: 5, can: "เขียน Backend API ให้แอปส่งข้อมูลมาประมวลผลแล้วรับผลกลับ" },
    { name: "Firebase", lv: 5, can: "เก็บข้อมูลผู้ใช้ และตั้งสิทธิ์ว่าใครเห็นข้อมูลไหนได้บ้าง" },
  ]},
  { group: "Systems & Security", items: [
    { name: "OSINT", lv: 6, can: "ค้นและเชื่อมเบาะแสจากข้อมูลสาธารณะจนหาคำตอบเจอ" },
    { name: "Reverse Engineering", lv: 5, can: "แกะไฟล์ Android APK เพื่อดูว่าโปรแกรมทำงานยังไง" },
    { name: "C++ / Algorithm", lv: 5, can: "แก้โจทย์อัลกอริทึมใต้เวลาจำกัดได้ถึง*รอบชิง* IT CLASH Coding Track" },
    { name: "ADB / WebSocket", lv: 4, can: "ทำให้มือถือกับ PC เชื่อมกันเอง เสียบสายแล้วใช้ได้ทันที" },
  ]},
  { group: "Game", items: [
    { name: "Gaming", lv: 10, max: true, can: "*Immortal* ใน Valorant และ Top Server ใน ROV" },
    { name: "Unity / C# (Game Dev)", lv: 3, can: "ทำเกม 2D ที่เล่นได้จริงภายใน *3 วัน*" },
  ]},
];

// Gaming records.
window.GAMING = [
  { game: "VALORANT", rank: "Immortal", sub: "Competitive", ign: "Rurtt#Ray", img: "assets/g-val.webp", cap: "Valorant lobby" },
  { game: "Minecraft · Ranked Bedwars", rank: "$200 International Champion", sub: "AXORA International Cup · ส.ค. 2568 · Prize pool $200 · ทีมไทยชนะ 3–2 ในรอบชิง", ign: "Reigards", img: "assets/g-bw.webp", pos: "left top", cap: "ประกาศผล AXORA International Cup" },
  { game: "Legends of Runeterra", rank: "Master #425", sub: "จากผู้เล่นระดับ Master ทั้งหมด 5,199 คน", img: "assets/g-lor.webp", cap: "Leaderboard ระดับ Master" },
  { game: "ROV", rank: "Top Server Maloch", sub: "ผู้เล่น ROV 100 ดาว · อายุน้อยร้อยดาว · 6,270 เกม · Win rate 56.4%", ign: "สกิบิดี้บิดี้บิดู้", img: "assets/g-rov.webp", fit: "contain", cap: "โปรไฟล์ ROV" },
];

// Quest log, newest first. rarity: legendary | epic | rare. fit: "contain" for transparent/diagram covers.
window.QUESTS = [
  {
    id: "docode",
    main: 4,
    date: "2568 – ปัจจุบัน", year: "Ongoing",
    title: "DoCode",
    event: "ฟรีแลนซ์รับทำเว็บไซต์และ SEO",
    result: "Founder · *ลูกค้าจริง*: บจก. เอส.อาร์.เซอร์วิส เอ็กเพรส",
    rarity: "epic",
    level: "ธุรกิจจริง",
    role: "Founder · Design · Frontend",
    cover: "assets/dc-home.webp",
    live: "https://sr-service-express.vercel.app",
    summary: "รับทำเว็บไซต์และ SEO แบบทำเองครบวงจร ตั้งแต่ทักลูกค้า คุยว่าเขาต้องการอะไร ตีขอบเขตให้พอดีงบ ไปจนถึงแจกงานให้ทีม Dev",
    brief: [
      "เว็บไซต์ลูกค้าทำด้วย Next.js แบบ Static Website พร้อมปรับ SEO",
      "เลือกไม่ใช้ Backend เพราะเป้าหมายคือนำเสนอข้อมูลและให้ลูกค้าเจอผ่าน Search Engine ลดภาระดูแลระบบ",
    ],
    did: [
      "หาและติดต่อผู้ว่าจ้าง วิเคราะห์เว็บไซต์เดิม เก็บความต้องการ",
      "กำหนดขอบเขตงานให้เหมาะกับงบประมาณ วางแผนและมอบหมายงาน",
      "ดูแลการออกแบบ และร่วมพัฒนา Frontend",
    ],
    stack: ["Next.js", "Static Site", "SEO"],
    loot: "Product ที่ดีเป็นแค่หนึ่งส่วนของธุรกิจ ส่วนที่ยากกว่าคือหาว่าจะสร้างคุณค่าตรงไหน และทำให้ลูกค้ามองเห็นคุณค่านั้น",
    note: "เขียนโค้ดง่ายกว่าหาลูกค้าเยอะ ตอนนี้เข้าใจแล้วว่าทำไมเซลส์ถึงเก่ง",
    gallery: [
      { src: "assets/dc-home.webp", cap: "เว็บไซต์ลูกค้า · หน้าแรก" },
      { src: "assets/dc-about.webp", cap: "หน้าแนะนำบริษัท" },
      { src: "assets/dc-services.webp", cap: "หน้ารวมบริการ" },
      { src: "assets/dc-mobile.webp", cap: "มุมมองบนมือถือ" },
      { src: "assets/dc-client.webp", cap: "ส่งมอบงานให้ลูกค้า" },
      { src: "assets/dc-qr.webp", cap: "QR เปิดเว็บ Live Preview" },
    ],
  },
  {
    id: "ctf",
    main: 1,
    date: "ส.ค. 2569", year: "2026",
    title: "Thailand Cyber Top Talent 2026",
    event: "TCTT 2026 · การแข่งขัน CTF ระดับ Junior · สกมช. (NCSA)",
    result: "*อันดับ 8 ของประเทศ* ทั้งประเภททีมและบุคคล · อันดับ 4 ภาคกลาง (ทีม)",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "Web Security · Reverse Engineering · Crypto · OSINT",
    duration: "เตรียมตัว 7 วัน",
    cover: "assets/ctf-map.webp",
    summary: "ลองลงแข่ง CTF ระดับประเทศทั้งที่พื้นฐาน Cybersecurity แทบเป็นศูนย์ มีเวลาเตรียมตัวประมาณ 7 วัน สุดท้ายติดอันดับ 8 ของประเทศ",
    brief: [
      "CTF (Capture The Flag) คือการแข่งขันด้าน Cybersecurity ผู้เล่นต้องหาช่องโหว่หรือไขปริศนาในโจทย์ เพื่อค้นหา “Flag” รหัสลับที่ซ่อนอยู่ แล้วส่งเพื่อเก็บคะแนน",
      "โจทย์ครอบคลุม Web Application Security, Reverse Engineering, Cryptography และ OSINT",
      "อันดับ 8 ของประเทศประเภทบุคคลในรอบคัดเลือก",
    ],
    did: [
      "OSINT: ค้นหาและเชื่อมโยงเบาะแสจากแหล่งข้อมูลสาธารณะ (ถนัดสุด)",
      "Reverse Engineering: วิเคราะห์โครงสร้างและพฤติกรรมโปรแกรม ตรวจ Android APK ด้วย Android Studio และ Log",
      "Web Security และ Cryptography: หาจุดอ่อนของระบบ ถอดรหัสข้อมูลเพื่อหา Flag",
    ],
    stack: ["OSINT", "Reverse Engineering", "Android Studio", "Web Security", "Cryptography"],
    loot: "เรียนเรื่องใหม่ใต้เวลาจำกัด ทดลองเครื่องมือจริง และเปลี่ยนวิธีคิดทันทีเมื่อทางเดิมไม่เวิร์ก",
    note: "ใช้เวลาแค่ 7 วันในการเรียนรู้พื้นฐาน เกือบตาย",
    gallery: [
      { src: "assets/ctf-map.webp", cap: "Scoreboard ระหว่างแข่ง" },
      { src: "assets/ctf-rank.webp", cap: "ประกาศรายชื่อผู้ได้รับเหรียญ" },
      { src: "assets/ctf-award.webp", cap: "รับเหรียญ" },
      { src: "assets/ctf-cert2.webp", cap: "ประกาศนียบัตร Thailand Cyber Top Talent 2026" },
      { src: "assets/ctf-cert.webp", cap: "Certificate of Participation" },
    ],
  },
  {
    id: "wordflow",
    main: true, hero: true,
    date: "พ.ค. – ส.ค. 2569", year: "2026",
    title: "WordFlow",
    event: "การแข่งขันพัฒนาโปรแกรมคอมพิวเตอร์แห่งประเทศไทย ครั้งที่ 28 (NSC)",
    result: "*ได้รับทุนสนับสนุน*การพัฒนาผลงาน NSC ครั้งที่ 28",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "Product Manager · Backend · Dashboard",
    duration: "4 เดือน",
    cover: "assets/wf-app.webp", fit: "contain", video: "assets/wf-demo.mp4", poster: "assets/wf-poster.webp",
    origin: [
      "เวลาพูดถึงเด็กที่ต้องการความช่วยเหลือ คนส่วนใหญ่มักนึกถึงภาวะที่เห็นชัด ๆ ก่อน แต่เด็ก LD ที่อยู่ตรงกลางกลับถูกมองข้าม ทั้งที่เด็กประมาณ 1 ใน 14 คนมีภาวะนี้ และเขาก็ต้องการความช่วยเหลือไม่ต่างกัน",
      "เครื่องมือที่มีตอนนี้ยังไม่พอ การได้พบแพทย์ต้องใช้เงิน และทางเลือกที่ถูกกว่านั้นแทบไม่มีเลย",
      "ที่ทำต่อมาได้ 4 เดือน เพราะเชื่อว่างานนี้อาจเป็นความหวังของใครสักคน และช่วยเขาได้จริง ๆ",
    ],
    summary: "เกมฝึกอ่านภาษาไทยสำหรับเด็กที่มีภาวะบกพร่องทางการเรียนรู้ (LD) เด็กเล่นเกมไป ฝึกอ่านไป แล้วมี AI ช่วยฟังว่าออกเสียงถูกไหมในระดับหน่วยเสียง",
    brief: [
      "เปลี่ยนแบบฝึกอ่านที่น่าเบื่อให้เป็นเกมผจญภัย เด็กต้องประกอบคำและออกเสียงเพื่อดำเนินเนื้อเรื่อง",
      "ใช้โมเดล ReVoiceAI (Wav2Vec2-BERT-Thai-IPA) วิเคราะห์ความถูกต้องของการออกเสียงระดับหน่วยเสียง อ้างอิงสัทอักษรสากล (IPA) พร้อมบันทึกเวลาตอบสนอง",
      "Dashboard ให้แพทย์และผู้ปกครองติดตามผลการฝึกได้ต่อเนื่อง",
      "ได้รับคำปรึกษาเชิงคลินิกจาก RainyKids Clinic และอยู่ระหว่างประสานงานทดสอบกับสถาบันการแพทย์จักรีนฤบดินทร์",
    ],
    did: [
      "ศึกษาปัญหา กำหนดทิศทางผลิตภัณฑ์ วางแผนและประสานงานในทีม",
      "ประสานงานกับบุคลากรทางการแพทย์ จัดทำเอกสาร และนำเสนอผลงาน",
      "พัฒนา Backend, Dashboard และ UX/UI บางส่วน",
      "ออกแบบ Data Flow และระบบสิทธิ์เข้าถึงข้อมูลเด็ก",
      "ตัดสินใจให้โมเดลเสียงรันบน Server เพราะโมเดลใหญ่ และอัปเดตได้โดยไม่ต้องออกแอปใหม่",
    ],
    stack: ["Unity", "C#", "FastAPI", "ReVoiceAI Model", "Firebase", "Next.js"],
    loot: "ซอฟต์แวร์ที่มีคุณค่าไม่ได้จบแค่ระบบทำงานได้ ต้องเหมาะกับผู้ใช้ เคารพข้อมูลที่ละเอียดอ่อน และผ่านการทดสอบก่อนใช้จริง",
    note: "โปรเจกต์ที่ทำให้นอนน้อยที่สุด แต่ก็ภูมิใจที่สุด เพราะรู้ว่ามีเด็ก ๆ รอใช้อยู่จริง",
    gallery: [
      { src: "assets/wf-app.webp", cap: "หน้าจอเกมบนมือถือ" },
      { src: "assets/wf-dash.webp", cap: "Dashboard สำหรับแพทย์และผู้ปกครอง" },
      { src: "assets/wf-arch.webp", cap: "System Architecture" },
      { src: "assets/wf-loop.webp", cap: "Gameplay Loop" },
      { src: "assets/wf-demo.webp", cap: "สาธิตผลงาน" },
      { src: "assets/wf-cert.webp", cap: "หนังสือรับรองทุน NSC ครั้งที่ 28" },
    ],
  },
  {
    id: "itclash",
    date: "พ.ค. 2569", year: "2026",
    title: "IT CLASH 69",
    event: "การแข่งขันทักษะทางวิชาการด้าน IT · คณะเทคโนโลยีสารสนเทศ สจล.",
    result: "ผ่านเข้า*รอบชิงชนะเลิศ* (Coding Track)",
    rarity: "epic",
    level: "ระดับชาติ",
    role: "ผู้แข่งขัน Coding Track",
    cover: "assets/it-cert.webp", fit: "contain",
    summary: "ลงแข่งสาย Coding Track ในงาน IT CLASH ของคณะ IT สจล. แก้โจทย์ไปเรื่อย ๆ รู้ตัวอีกทีก็เข้ารอบชิงชนะเลิศแล้ว",
    brief: [
      "แข่งแก้โจทย์เขียนโปรแกรมในสาย Coding Track",
      "ผ่านรอบคัดเลือกเข้าสู่รอบชิงชนะเลิศ",
    ],
    did: [
      "แก้โจทย์เขียนโปรแกรมภายใต้เวลาจำกัด",
      "ใช้พื้นฐานอัลกอริทึมจากค่าย สอวน. ต่อยอดในสนามจริง",
    ],
    stack: ["Competitive Programming", "Algorithm", "Problem Solving"],
    loot: "พื้นฐานที่ปูไว้ตั้งแต่ค่าย สอวน. เอามาใช้ได้จริงเมื่อถึงเวลาแข่ง",
    note: "ถ้วยไม่ได้ แต่ได้เข้ารอบชิงกับประสบการณ์กลับบ้าน ก็คุ้มแล้ว",
    gallery: [
      { src: "assets/it-cert.webp", cap: "เกียรติบัตรผู้เข้ารอบชิงชนะเลิศ IT CLASH 69" },
    ],
  },
  {
    id: "gamejam",
    date: "เม.ย. 2569", year: "2026",
    title: "Gimme Your Place",
    event: "HamsterHub GameJamX",
    result: "สร้างเกม Local Co-op เล่นได้จริงใน *3 วัน*",
    rarity: "rare",
    level: "ระดับชาติ",
    role: "Game Programmer · Game Designer",
    duration: "3 วัน",
    cover: "assets/gj-game.webp",
    summary: "เกม 2D แบบ Local Co-op ที่ให้เพื่อนแข่งกันไปเส้นชัย แต่ตัวละครสลับกันได้ และมี Event ป่วนตลอดเวลา เหมาะมากสำหรับทำลายมิตรภาพ",
    brief: [
      "Event เปลี่ยนเงื่อนไขการเล่น เช่น ถังระเบิด สลับปุ่มควบคุม และลดความเร็ว",
      "ตอนนั้นพื้นฐาน Game Development ยังน้อยมาก เรียนไปทำไป",
    ],
    did: [
      "ออกแบบและเขียน Mechanic สลับตัวละคร",
      "ออกแบบและเขียนระบบ Event",
      "กำหนดขอบเขตให้ทีมเปลี่ยนไอเดียเป็นเกมที่เล่นได้จริงทันเวลา",
    ],
    stack: ["Unity", "C#", "Game Design", "Rapid Prototyping"],
    loot: "เวลาน้อยต้องทำ Mechanic หลักที่สนุกให้ได้ก่อน ฟีเจอร์อื่นค่อยตามมา",
    note: "เล่นเกมมาทั้งชีวิต เพิ่งรู้ว่าทำเกมยากกว่าเล่นเยอะ ขอโทษ Dev ทุกคนที่เคยบ่นไว้",
    gallery: [
      { src: "assets/gj-game.webp", cap: "หน้าจอเกม" },
      { src: "assets/gj-cert.webp", cap: "Certificate of Participation" },
    ],
  },
  {
    id: "subtrack",
    date: "ก.พ. 2569", year: "2026",
    title: "SubTrack",
    event: "L@UNCHL4B: Build in Public AI-Powered Startup Hackathon",
    result: "*ชนะเลิศ* · เงินรางวัล 10,000 บาท",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "Product Manager · Frontend",
    duration: "12 ชั่วโมง",
    cover: "assets/st-app.webp",
    summary: "เว็บแอปรวม Subscription ทุกเจ้าไว้ที่เดียว ดึงข้อมูลจากอีเมลชำระเงินมาโชว์บน Dashboard กับปฏิทิน จะได้รู้ตัวว่าเดือนนี้โดนตัดเงินไปกี่บาทแล้ว",
    brief: [
      "Hackathon ครั้งแรก ต้องสร้าง Product ใช้งานได้จริงจากศูนย์ภายใน 12 ชั่วโมง",
      "คู่แข่งส่วนใหญ่เป็นนักศึกษามหาวิทยาลัย",
      "ได้สิทธิ์พิจารณาทุนต่อยอดจาก TED Fund สูงสุด 1.5 ล้านบาท",
    ],
    did: [
      "แปลงไอเดียทีมเป็นขอบเขต MVP และจัดลำดับความสำคัญของฟีเจอร์",
      "พัฒนา Flow เชื่อม Gmail ฝั่ง Frontend และนำข้อมูลจาก API มาแสดงผล",
      "ขอสิทธิ์ Gmail แบบอ่านอย่างเดียว เพื่อความปลอดภัยของผู้ใช้",
      "เตรียม Mock Data สำรองเมื่อ Backend ไม่พร้อม ทำให้เดโม User Flow ได้ครบ",
      "นำเสนอผลงานต่อคณะกรรมการ",
    ],
    stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Google OAuth 2.0", "Gmail API"],
    loot: "ใช้ AI เร่งความเร็วได้ แต่คนต้องเป็นคนกำหนดโจทย์ ตรวจผลลัพธ์ และตัดสินใจให้ตรงเป้าหมายของผลิตภัณฑ์",
    note: "ในห้องเต็มไปด้วยพี่ ๆ มหาลัย แต่อยากได้ตังค์ ทำไงได้",
    gallery: [
      { src: "assets/hero.webp", cap: "ถ้วยชนะเลิศ + เงินรางวัล 10,000 บาท" },
      { src: "assets/st-app.webp", cap: "SubTrack ตอนเดโม" },
      { src: "assets/st-stage.webp", cap: "ขึ้นเวทีนำเสนอ" },
    ],
  },
  {
    id: "zeitop",
    main: 2,
    date: "พ.ย. 2568", year: "2025",
    title: "ZeiTop",
    event: "SK Robotics Playground 2025",
    result: "*เหรียญทอง* · รองชนะเลิศอันดับ 3 โครงงานซอฟต์แวร์และธุรกิจ",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "System Integration · ผู้นำเสนอหลัก",
    cover: "assets/zt-macro-bg.webp", fit: "contain",
    summary: "แอป Open Source ที่ชุบชีวิตมือถือ Android เครื่องเก่าให้กลายเป็นจอเสริม Macropad หรือแผงควบคุมของ PC เสียบสายปุ๊บ ใช้ได้ปั๊บ",
    brief: [
      "ฝั่ง PC เขียนด้วย Rust + Tokio ฝั่ง Android ใช้ Apache Cordova",
      "สื่อสารกันผ่าน WebSocket บนสาย USB",
      "แยกความสามารถเป็น Service ผู้ใช้สร้างหน้าควบคุมเองได้โดยไม่ต้องแก้ระบบหลัก",
    ],
    did: [
      "พัฒนากระบวนการตรวจจับอุปกรณ์ ติดตั้งและเปิดแอปอัตโนมัติผ่าน ADB",
      "ใช้ ADB reverse ต่อ Android Client เข้า WebSocket บน PC ให้เสียบแล้วใช้ได้เลย",
      "นำเสนอผลงานและตอบคำถามคณะกรรมการเป็นหลัก",
    ],
    stack: ["Rust", "Tokio", "Apache Cordova", "WebSocket", "ADB"],
    loot: "ประสบการณ์ผู้ใช้เริ่มตั้งแต่วินาทีแรกที่เสียบสาย ขั้นตอนติดตั้งสำคัญพอ ๆ กับฟีเจอร์",
    note: "มือถือเก่าในลิ้นชักทุกบ้าน ขอเกิดใหม่เป็น Macropad แม่จะได้เลิกถามว่าเก็บไว้ทำไม",
    gallery: [
      { src: "assets/zt-macro-bg.webp", cap: "โหมด Macropad" },
      { src: "assets/zt-clock-bg.webp", cap: "โหมด Desktop Clock" },
      { src: "assets/zt-arch.webp", cap: "ระบบการทำงาน" },
      { src: "assets/zt-team.webp", cap: "ทีมในวันแข่ง" },
      { src: "assets/zt-cert.webp", cap: "เกียรติบัตรเหรียญทอง" },
      { src: "assets/zt-cert2.webp", cap: "เกียรติบัตรรองชนะเลิศอันดับ 3 เหรียญทอง" },
    ],
  },
  {
    id: "ict",
    date: "พ.ย. 2568", year: "2025",
    title: "ICT Challenge 2025",
    event: "การแข่งขันตอบปัญหาวิชาการคอมพิวเตอร์และ IT ระดับ ม.ปลาย ครั้งที่ 15 · SIT มจธ.",
    result: "ผ่านเข้ารอบคัดเลือก *30 ทีม*",
    rarity: "rare",
    level: "ระดับชาติ",
    role: "ผู้แข่งขัน",
    cover: "assets/ict-cert.webp", fit: "contain",
    summary: "การแข่งขันตอบปัญหาวิชาการคอมพิวเตอร์และ IT ระดับ ม.ปลาย ของคณะ IT มจธ. ลงแข่งเป็นทีมกับเพื่อน และผ่านเข้ารอบ 30 ทีม",
    brief: [
      "ตอบปัญหาวิชาการคอมพิวเตอร์และเทคโนโลยีสารสนเทศระดับมัธยมปลาย",
      "ผ่านเข้ารอบคัดเลือก 30 ทีมจากทั่วประเทศ",
    ],
    did: [
      "ทบทวนความรู้ด้านคอมพิวเตอร์ อัลกอริทึม และเทคโนโลยีสารสนเทศ",
      "แข่งขันเป็นทีม แบ่งหน้าที่ตามความถนัดของแต่ละคน",
    ],
    stack: ["Computer Science", "IT Knowledge", "Teamwork"],
    loot: "รู้ว่าความรู้ทฤษฎีสำคัญพอ ๆ กับการลงมือสร้าง ทั้งสองอย่างต้องไปด้วยกัน",
    note: "สนามแรกของการแข่งตอบปัญหาแบบทีม ได้เข้ารอบ 30 ทีม ครั้งหน้าไปให้ไกลกว่านี้",
    gallery: [
      { src: "assets/ict-cert.webp", cap: "เกียรติบัตรผ่านเข้ารอบ 30 ทีม ICT Challenge 2025" },
    ],
  },
  {
    id: "posn",
    main: 3,
    date: "ต.ค. 2568", year: "2025",
    title: "ค่าย 1 สอวน. คอมพิวเตอร์",
    event: "โครงการโอลิมปิกวิชาการ สอวน. สาขาคอมพิวเตอร์",
    result: "ผ่านการคัดเลือกเข้าค่าย 1",
    rarity: "epic",
    level: "ระดับภาค",
    role: "ผู้เข้าค่าย",
    cover: "assets/posn-photo.webp",
    summary: "จุดเริ่มต้นของการเขียนโปรแกรมแบบจริงจัง ได้เรียน C++ และอัลกอริทึมอย่างเป็นระบบครั้งแรก และเป็นจุดที่เปลี่ยนวิธีเรียนของผมไปเลย",
    brief: [
      "ก่อนหน้านี้ลงแข่งเทคโนโลยีมาหลายรายการแต่ยังไม่สำเร็จ จนรู้ว่าความสนใจอย่างเดียวไม่พอ ต้องเรียนให้เป็นระบบ",
      "สอบผ่านการคัดเลือกเข้าค่าย 1 โครงการโอลิมปิกวิชาการ สอวน. สาขาคอมพิวเตอร์",
      "เรียนเขียนโปรแกรมภาษา C++ และอัลกอริทึม ผ่านโจทย์ที่ต้องวิเคราะห์เงื่อนไข ออกแบบวิธีแก้ และคิดทั้งความถูกต้องและประสิทธิภาพ",
      "ได้เจอเพื่อนที่ชอบเรื่องเดียวกัน และแก้โจทย์ไปด้วยกัน",
    ],
    did: [
      "ฝึกเขียน C++ และแก้โจทย์อัลกอริทึม",
      "ฝึกแตกปัญหาใหญ่เป็นขั้นเล็ก ๆ ก่อนเริ่มเขียนโค้ด",
      "เรียนรู้ว่าโปรแกรมที่ดีไม่ใช่แค่รันผ่าน แต่ต้องเร็วพอด้วย",
    ],
    stack: ["C++", "Algorithm", "Problem Solving"],
    loot: "ไม่ได้ไปต่อค่าย 2 แต่ได้วิธีคิดแบบเป็นขั้นตอนที่ใช้ต่อในทุกโปรเจกต์หลังจากนั้น และรู้ตัวว่าชอบการแก้ปัญหาจริง ๆ",
    note: "ไม่ได้ไปค่าย 2 แต่ได้ C++ กับเพื่อนสายคอมติดมือกลับบ้าน ถือว่ากำไร",
    gallery: [
      { src: "assets/posn-photo.webp", cap: "รับเกียรติบัตรค่าย 1" },
      { src: "assets/posn-cert.webp", cap: "เกียรติบัตร" },
    ],
  },
  {
    id: "rov",
    date: "ม.ค. 2568", year: "2025",
    title: "depa E-Sports In Schools",
    event: "การแข่งขัน E-Sports เกม ROV",
    result: "*รองชนะเลิศอันดับ 2* · เงินรางวัล 2,000 บาท",
    rarity: "epic",
    level: "ระดับโรงเรียน",
    role: "ผู้เล่น · IGN สกิบิดี้บิดี้บิดู้",
    cover: "assets/rov-1.webp",
    summary: "เล่น ROV กับเพื่อนมาตลอด เลยลองลงแข่งรายการ depa E-Sports In Schools ดู ได้รองชนะเลิศอันดับ 2 กลับมา และทำให้รู้ว่าชอบวางแผนกับทำงานเป็นทีม",
    brief: [
      "วางแผนรูปแบบการเล่น วิเคราะห์คู่แข่ง และตัดสินใจร่วมกันในสถานการณ์ที่เปลี่ยนเร็วมาก",
    ],
    did: [
      "สื่อสารและประสานงานกับทีมระหว่างเกม",
      "วิเคราะห์คู่แข่งและปรับแผนตามสถานการณ์",
    ],
    stack: ["Teamwork", "Shotcalling", "Decision Making"],
    loot: "ฝีมือแต่ละคนมีประโยชน์สูงสุดเมื่อทุกคนเข้าใจบทบาทของตัวเองและเล่นเป็นทีม",
    note: "ชื่อในเกมอาจดูไม่จริงจัง แต่เรื่องเล่นเป็นทีม จริงจังนะ",
    gallery: [
      { src: "assets/rov-1.webp", cap: "ทีมรับรางวัล" },
      { src: "assets/rov-2.webp", cap: "บนเวที" },
      { src: "assets/g-rov.webp", cap: "โปรไฟล์ ROV" },
    ],
  },
];
