// All site content lives here. Edit values, refresh page. No build step.

// Attribute chart. value = 0-100: radar shape + top 6 as bars on the hero card. can = what I can do in this field.
window.STATS = [
  { key: "Product", value: 92, can: "ตีโจทย์ให้ชัด วาง MVP และพาทีมส่งงานจนจบ" },
  { key: "AI", value: 88, can: "มี Wiki และ Skill ของตัวเอง ใช้ Token คุ้ม เซฟงานทุกขั้น AI รู้บริบทเองโดยไม่ต้องเล่าซ้ำ" },
  { key: "Clutch", value: 90, can: "ส่งงานได้ใต้เวลาบีบ เช่น Hackathon 12 ชม. หรือเตรียม CTF 7 วัน" },
  { key: "Pitch", value: 85, can: "เล่าโปรเจกต์ให้เข้าใจง่าย และตอบคำถามกรรมการได้ตรงจุด" },
  { key: "Teamwork", value: 88, can: "แบ่งงานตามความถนัด และพาทีมไปทางเดียวกัน" },
  { key: "Web", value: 72, can: "ทำเว็บตั้งแต่หน้าบ้านถึงหลังบ้าน ส่งลูกค้าจริงได้" },
  { key: "Systems", value: 62, can: "ต่อหลายระบบให้คุยกันได้ เช่น PC กับมือถือผ่านสาย USB" },
  { key: "Security", value: 65, can: "สืบข้อมูล OSINT และแกะโปรแกรมหาจุดอ่อนได้" },
  { key: "Game Dev", value: 30, can: "ทำเกมเล่นได้จริงใน 3 วัน ยังฝึกอยู่" },
];

// Skill tree. lv = 1-10. max: true shows "MAX". can = what this level actually did.
window.SKILLS = [
  { group: "Product & Team", items: [
    { name: "Product Management", lv: 8, can: "คุมทีม *3–6 คน*ให้โฟกัสและส่งงานจนจบโดยไม่หมดไฟ" },
    { name: "MVP Scoping", lv: 9, can: "ตัดไอเดียให้เหลือ MVP ที่เดโมได้ภายใน *12 ชม.*" },
    { name: "Pitching / ตอบกรรมการ", lv: 8, can: "เล่าโปรเจกต์ให้เข้าใจง่าย และตอบคำถามกรรมการได้ตรงจุด" },
  ]},
  { group: "AI Tools", items: [
    { name: "Claude / Claude Code", lv: 9, can: "สร้าง Wiki และ Skill ของตัวเอง ให้ AI เข้าใจบริบทงานโดยไม่ต้องเล่าซ้ำ" },
    { name: "Codex", lv: 8, can: "ใช้ Token อย่างคุ้มค่า และเซฟความคืบหน้างานได้ทุกขั้น" },
    { name: "AI Model Integration", lv: 5, can: "ต่อโมเดล AI ขึ้น Server ให้แอปเรียกใช้ผ่าน API ได้" },
  ]},
  { group: "Web & Backend", items: [
    { name: "React + TypeScript", lv: 6, can: "ทำเว็บที่ล็อกอินด้วย Google และดึงข้อมูลจาก API มาแสดงได้" },
    { name: "Next.js", lv: 6, can: "ทำเว็บพร้อม SEO ส่งให้*ลูกค้าจริง*ใช้งานได้" },
    { name: "FastAPI / Python", lv: 5, can: "เขียน Backend API ให้แอปส่งข้อมูลมาประมวลผลแล้วรับผลกลับ" },
    { name: "Firebase", lv: 5, can: "เก็บข้อมูลผู้ใช้ และตั้งสิทธิ์ว่าใครเห็นข้อมูลไหนได้บ้าง" },
  ]},
  { group: "Systems & Security", items: [
    { name: "OSINT", lv: 6, can: "ค้นและเชื่อมเบาะแสจากข้อมูลสาธารณะจนหาคำตอบเจอ" },
    { name: "Reverse Engineering", lv: 5, can: "แกะไฟล์ Android APK เพื่อดูว่าโปรแกรมทำงานยังไง" },
    { name: "C++ / Algorithm", lv: 5, can: "แก้โจทย์อัลกอริทึมใต้เวลาจำกัดได้ถึง*รอบชิง* IT CLASH Coding Track" },
    { name: "ADB / WebSocket", lv: 4, can: "ทำให้มือถือกับ PC เชื่อมกันเอง เสียบสายแล้วใช้ได้ทันที" },
  ]},
  { group: "Game", items: [
    { name: "Gaming", lv: 10, max: true, can: "*Immortal* ใน Valorant และ Top Server ใน ROV" },
    { name: "Unity / C# (Game Dev)", lv: 3, can: "ทำเกม 2D ที่เล่นได้จริงภายใน *3 วัน*" },
  ]},
];

// Gaming records. Not rendered right now (Valorant sits in the hobby section as static HTML), kept to add back later.
window.GAMING = [
  { game: "VALORANT", rank: "Immortal", sub: "Competitive", ign: "Rurtt#Ray", img: "assets/g-val.webp", cap: "Valorant lobby" },
  { game: "Minecraft · Ranked Bedwars", rank: "$200 International Champion", sub: "AXORA International Cup · ส.ค. 2568 · Prize pool $200 · ทีมไทยชนะ 3–2 ในรอบชิง", ign: "Reigards", img: "assets/g-bw.webp", pos: "left top", cap: "ประกาศผล AXORA International Cup" },
  { game: "Legends of Runeterra", rank: "Master #425", sub: "จากผู้เล่นระดับ Master ทั้งหมด 5,199 คน", img: "assets/g-lor.webp", cap: "Leaderboard ระดับ Master" },
  { game: "ROV", rank: "Top Server Maloch", sub: "ผู้เล่น ROV 100 ดาว · อายุน้อยร้อยดาว · 6,270 เกม · Win rate 56.4%", ign: "สกิบิดี้บิดี้บิดู้", img: "assets/g-rov.webp", fit: "contain", cap: "โปรไฟล์ ROV" },
];

// Quest log, newest first. rarity: legendary | epic | rare. fit: "contain" for transparent/diagram covers.
// Quest page: keep brief/did at 1-2 short bullets, loot/note one short line (judges skim). origin is kept but not rendered.
window.QUESTS = [
  {
    id: "docode",
    main: 4,
    date: "2568 – ปัจจุบัน", year: "Ongoing",
    title: "DoCode",
    event: "ฟรีแลนซ์รับทำเว็บไซต์และ SEO",
    result: "Founder · *ลูกค้าจริง*: บจก. เอส.อาร์.เซอร์วิส เอ็กเพรส",
    rarity: "epic",
    level: "ธุรกิจจริง",
    role: "Founder · Design · Frontend",
    cover: "assets/dc-home.webp",
    live: "https://sr-service-express.vercel.app",
    summary: "รับทำเว็บไซต์และ SEO ครบวงจร ตั้งแต่คุยกับลูกค้าจนส่งงาน",
    brief: [
      "เว็บลูกค้าทำด้วย Next.js แบบ Static พร้อม SEO",
      "ไม่ใช้ Backend เพื่อลดภาระดูแลระบบ",
    ],
    did: [
      "หาลูกค้า ตีขอบเขตให้พอดีงบ แล้วแจกงานให้ทีม",
      "ออกแบบ และร่วมทำ Frontend",
    ],
    stack: ["Next.js", "Static Site", "SEO"],
    loot: "Product ดีเป็นแค่ส่วนหนึ่ง ที่ยากกว่าคือทำให้ลูกค้าเห็นคุณค่า",
    note: "เขียนโค้ดง่ายกว่าหาลูกค้าเยอะ",
    gallery: [
      { src: "assets/dc-home.webp", cap: "เว็บไซต์ลูกค้า · หน้าแรก" },
      { src: "assets/dc-about.webp", cap: "หน้าแนะนำบริษัท" },
      { src: "assets/dc-services.webp", cap: "หน้ารวมบริการ" },
      { src: "assets/dc-mobile.webp", cap: "มุมมองบนมือถือ" },
      { src: "assets/dc-client.webp", cap: "ส่งมอบงานให้ลูกค้า" },
      { src: "assets/dc-qr.webp", cap: "QR เปิดเว็บ Live Preview" },
    ],
  },
  {
    id: "ctf",
    main: 1,
    date: "ส.ค. 2569", year: "2026",
    title: "Thailand Cyber Top Talent 2026",
    event: "TCTT 2026 · การแข่งขัน CTF ระดับ Junior · สกมช. (NCSA)",
    result: "*อันดับ 8 ของประเทศ* ทั้งประเภททีมและบุคคล · อันดับ 4 ภาคกลาง (ทีม)",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "Web Security · Reverse Engineering · Crypto · OSINT",
    duration: "เตรียมตัว 7 วัน",
    cover: "assets/ctf-map.webp",
    summary: "แข่ง CTF (หาช่องโหว่เพื่อเก็บคะแนน) ทั้งที่พื้นฐานแทบเป็นศูนย์ เตรียมตัว 7 วัน ติดอันดับ 8 ของประเทศ",
    brief: [
      "CTF คือแข่งหาช่องโหว่หรือไขปริศนา เพื่อหา Flag มาเก็บคะแนน",
      "โจทย์มีทั้ง Web, Reverse Engineering, Crypto และ OSINT",
    ],
    did: [
      "OSINT: สืบเบาะแสจากข้อมูลสาธารณะ (ถนัดสุด)",
      "Reverse Engineering: แกะดูการทำงานของ Android APK",
    ],
    stack: ["OSINT", "Reverse Engineering", "Android Studio", "Web Security", "Cryptography"],
    loot: "เรียนของใหม่ใต้เวลาจำกัด ทางเดิมไม่เวิร์กก็เปลี่ยนทันที",
    note: "เรียนพื้นฐานใน 7 วัน เกือบตาย",
    gallery: [
      { src: "assets/ctf-map.webp", cap: "Scoreboard ระหว่างแข่ง" },
      { src: "assets/ctf-rank.webp", cap: "ประกาศรายชื่อผู้ได้รับเหรียญ" },
      { src: "assets/ctf-award.webp", cap: "รับเหรียญ" },
      { src: "assets/ctf-cert2.webp", cap: "ประกาศนียบัตร Thailand Cyber Top Talent 2026" },
      { src: "assets/ctf-cert.webp", cap: "Certificate of Participation" },
    ],
  },
  {
    id: "wordflow",
    main: true, hero: true,
    date: "พ.ค. – ส.ค. 2569", year: "2026",
    title: "WordFlow",
    event: "การแข่งขันพัฒนาโปรแกรมคอมพิวเตอร์แห่งประเทศไทย ครั้งที่ 28 (NSC)",
    result: "*ได้รับทุนสนับสนุน*การพัฒนาผลงาน NSC ครั้งที่ 28",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "Product Manager · Backend · Dashboard",
    duration: "4 เดือน",
    cover: "assets/wf-app.webp", fit: "contain", video: "assets/wf-demo.mp4", poster: "assets/wf-poster.webp",
    origin: [
      "เวลาพูดถึงเด็กที่ต้องการความช่วยเหลือ คนส่วนใหญ่มักนึกถึงภาวะที่เห็นชัด ๆ ก่อน แต่เด็ก LD ที่อยู่ตรงกลางกลับถูกมองข้าม ทั้งที่เด็กประมาณ 1 ใน 14 คนมีภาวะนี้ และเขาก็ต้องการความช่วยเหลือไม่ต่างกัน",
      "เครื่องมือที่มีตอนนี้ยังไม่พอ การได้พบแพทย์ต้องใช้เงิน และทางเลือกที่ถูกกว่านั้นแทบไม่มีเลย",
      "ที่ทำต่อมาได้ 4 เดือน เพราะเชื่อว่างานนี้อาจเป็นความหวังของใครสักคน และช่วยเขาได้จริง ๆ",
    ],
    summary: "เกมฝึกอ่านภาษาไทยสำหรับเด็ก LD มี AI ฟังว่าออกเสียงถูกไหม",
    brief: [
      "เปลี่ยนแบบฝึกอ่านให้เป็นเกมผจญภัย",
      "AI (ReVoiceAI) ฟังการออกเสียงระดับหน่วยเสียง",
    ],
    did: [
      "กำหนดทิศทางโปรดักต์ และคุมทีม",
      "ทำ Backend, Dashboard และคุยกับแพทย์",
    ],
    stack: ["Unity", "C#", "FastAPI", "ReVoiceAI Model", "Firebase", "Next.js"],
    loot: "ซอฟต์แวร์ที่ดีต้องเหมาะกับผู้ใช้ และเคารพข้อมูลที่ละเอียดอ่อน",
    note: "นอนน้อยที่สุด แต่ภูมิใจที่สุด",
    gallery: [
      { src: "assets/wf-app.webp", cap: "หน้าจอเกมบนมือถือ" },
      { src: "assets/wf-dash.webp", cap: "Dashboard สำหรับแพทย์และผู้ปกครอง" },
      { src: "assets/wf-arch.webp", cap: "System Architecture" },
      { src: "assets/wf-loop.webp", cap: "Gameplay Loop" },
      { src: "assets/wf-demo.webp", cap: "สาธิตผลงาน" },
      { src: "assets/wf-cert.webp", cap: "หนังสือรับรองทุน NSC ครั้งที่ 28" },
    ],
  },
  {
    id: "itclash",
    date: "พ.ค. 2569", year: "2026",
    title: "IT CLASH 69",
    event: "การแข่งขันทักษะทางวิชาการด้าน IT · คณะเทคโนโลยีสารสนเทศ สจล.",
    result: "ผ่านเข้า*รอบชิงชนะเลิศ* (Coding Track)",
    rarity: "epic",
    level: "ระดับชาติ",
    role: "ผู้แข่งขัน Coding Track",
    cover: "assets/it-cert.webp", fit: "contain",
    summary: "แข่งแก้โจทย์เขียนโปรแกรมสาย Coding Track จนเข้ารอบชิง",
    brief: [
      "แข่งแก้โจทย์เขียนโปรแกรม สาย Coding Track",
    ],
    did: [
      "แก้โจทย์ใต้เวลาจำกัด ด้วยพื้นฐานจากค่าย สอวน.",
    ],
    stack: ["Competitive Programming", "Algorithm", "Problem Solving"],
    loot: "พื้นฐานจากค่าย สอวน. เอามาใช้ได้จริงในสนาม",
    note: "ถ้วยไม่ได้ แต่ได้เข้ารอบชิง ก็คุ้มแล้ว",
    gallery: [
      { src: "assets/it-cert.webp", cap: "เกียรติบัตรผู้เข้ารอบชิงชนะเลิศ IT CLASH 69" },
    ],
  },
  {
    id: "gamejam",
    date: "เม.ย. 2569", year: "2026",
    title: "Gimme Your Place",
    event: "HamsterHub GameJamX",
    result: "สร้างเกม Local Co-op เล่นได้จริงใน *3 วัน*",
    rarity: "rare",
    level: "ระดับชาติ",
    role: "Game Programmer · Game Designer",
    duration: "3 วัน",
    cover: "assets/gj-game.webp",
    summary: "เกม 2D Local Co-op แข่งกันไปเส้นชัย ตัวละครสลับกันได้ เหมาะกับการทำลายมิตรภาพ",
    brief: [
      "มี Event ป่วนตลอด เช่น ถังระเบิด สลับปุ่มควบคุม",
      "ตอนนั้นยังทำเกมไม่ค่อยเป็น เรียนไปทำไป",
    ],
    did: [
      "เขียน Mechanic สลับตัวละคร และระบบ Event",
      "ตัดขอบเขตให้ทันใน 3 วัน",
    ],
    stack: ["Unity", "C#", "Game Design", "Rapid Prototyping"],
    loot: "เวลาน้อย ต้องทำ Mechanic หลักให้สนุกก่อน",
    note: "ทำเกมยากกว่าเล่นเยอะ ขอโทษ Dev ทุกคน",
    gallery: [
      { src: "assets/gj-game.webp", cap: "หน้าจอเกม" },
      { src: "assets/gj-cert.webp", cap: "Certificate of Participation" },
    ],
  },
  {
    id: "subtrack",
    date: "ก.พ. 2569", year: "2026",
    title: "SubTrack",
    event: "L@UNCHL4B: Build in Public AI-Powered Startup Hackathon",
    result: "*ชนะเลิศ* · เงินรางวัล 10,000 บาท",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "Product Manager · Frontend",
    duration: "12 ชั่วโมง",
    cover: "assets/st-app.webp",
    summary: "เว็บรวม Subscription ทุกเจ้า ดึงจากอีเมลมาโชว์ รู้ทันทีว่าเดือนนี้โดนตัดเงินไปเท่าไร",
    brief: [
      "Hackathon ครั้งแรก สร้างจากศูนย์ใน 12 ชั่วโมง",
      "คู่แข่งส่วนใหญ่เป็นนักศึกษามหาวิทยาลัย",
    ],
    did: [
      "ตีไอเดียทีมเป็น MVP และจัดลำดับฟีเจอร์",
      "ทำ Flow เชื่อม Gmail และนำเสนอต่อกรรมการ",
    ],
    stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Google OAuth 2.0", "Gmail API"],
    loot: "AI ช่วยเร่งได้ แต่คนต้องกำหนดโจทย์และตัดสินใจเอง",
    note: "ห้องเต็มไปด้วยพี่มหาลัย แต่อยากได้ตังค์ ทำไงได้",
    gallery: [
      { src: "assets/hero.webp", cap: "ถ้วยชนะเลิศ + เงินรางวัล 10,000 บาท" },
      { src: "assets/st-app.webp", cap: "SubTrack ตอนเดโม" },
      { src: "assets/st-stage.webp", cap: "ขึ้นเวทีนำเสนอ" },
    ],
  },
  {
    id: "zeitop",
    main: 2,
    date: "พ.ย. 2568", year: "2025",
    title: "ZeiTop",
    event: "SK Robotics Playground 2025",
    result: "*เหรียญทอง* · รองชนะเลิศอันดับ 3 โครงงานซอฟต์แวร์และธุรกิจ",
    rarity: "legendary",
    level: "ระดับชาติ",
    role: "System Integration · ผู้นำเสนอหลัก",
    cover: "assets/zt-macro-bg.webp", fit: "contain",
    summary: "ชุบชีวิตมือถือ Android เก่าเป็นจอเสริม / Macropad ของ PC เสียบสายปุ๊บ ใช้ได้ปั๊บ",
    brief: [
      "ฝั่ง PC เขียนด้วย Rust + Tokio ฝั่งมือถือใช้ Cordova",
      "คุยกันผ่าน WebSocket บนสาย USB",
    ],
    did: [
      "ทำให้เสียบสายแล้วติดตั้งและเปิดแอปเองผ่าน ADB",
      "นำเสนอและตอบคำถามกรรมการ",
    ],
    stack: ["Rust", "Tokio", "Apache Cordova", "WebSocket", "ADB"],
    loot: "ประสบการณ์ผู้ใช้เริ่มตั้งแต่วินาทีที่เสียบสาย",
    note: "มือถือเก่าในลิ้นชัก ขอเกิดใหม่เป็น Macropad",
    gallery: [
      { src: "assets/zt-macro-bg.webp", cap: "โหมด Macropad" },
      { src: "assets/zt-clock-bg.webp", cap: "โหมด Desktop Clock" },
      { src: "assets/zt-arch.webp", cap: "ระบบการทำงาน" },
      { src: "assets/zt-team.webp", cap: "ทีมในวันแข่ง" },
      { src: "assets/zt-cert.webp", cap: "เกียรติบัตรเหรียญทอง" },
      { src: "assets/zt-cert2.webp", cap: "เกียรติบัตรรองชนะเลิศอันดับ 3 เหรียญทอง" },
    ],
  },
  {
    id: "ict",
    date: "พ.ย. 2568", year: "2025",
    title: "ICT Challenge 2025",
    event: "การแข่งขันตอบปัญหาวิชาการคอมพิวเตอร์และ IT ระดับ ม.ปลาย ครั้งที่ 15 · SIT มจธ.",
    result: "ผ่านเข้ารอบคัดเลือก *30 ทีม*",
    rarity: "rare",
    level: "ระดับชาติ",
    role: "ผู้แข่งขัน",
    cover: "assets/ict-cert.webp", fit: "contain",
    summary: "แข่งตอบปัญหาคอมพิวเตอร์และ IT เป็นทีม ผ่านเข้ารอบ 30 ทีม",
    brief: [
      "ตอบปัญหาคอมพิวเตอร์และ IT ระดับ ม.ปลาย",
      "ผ่านเข้ารอบ 30 ทีมจากทั่วประเทศ",
    ],
    did: [
      "ทบทวนคอมพิวเตอร์ อัลกอริทึม และ IT",
      "แบ่งหน้าที่ในทีมตามความถนัด",
    ],
    stack: ["Computer Science", "IT Knowledge", "Teamwork"],
    loot: "ทฤษฎีกับการลงมือสร้าง ต้องไปด้วยกัน",
    note: "ครั้งหน้าไปให้ไกลกว่านี้",
    gallery: [
      { src: "assets/ict-cert.webp", cap: "เกียรติบัตรผ่านเข้ารอบ 30 ทีม ICT Challenge 2025" },
    ],
  },
  {
    id: "posn",
    main: 3,
    date: "ต.ค. 2568", year: "2025",
    title: "ค่าย 1 สอวน. คอมพิวเตอร์",
    event: "โครงการโอลิมปิกวิชาการ สอวน. สาขาคอมพิวเตอร์",
    result: "ผ่านการคัดเลือกเข้าค่าย 1",
    rarity: "epic",
    level: "ระดับภาค",
    role: "ผู้เข้าค่าย",
    cover: "assets/posn-photo.webp",
    summary: "ครั้งแรกที่เรียน C++ และอัลกอริทึมแบบจริงจัง",
    brief: [
      "สอบผ่านเข้าค่าย 1 สอวน. คอมพิวเตอร์",
      "เรียน C++ และอัลกอริทึมเป็นระบบครั้งแรก",
    ],
    did: [
      "ฝึก C++ และแก้โจทย์อัลกอริทึม",
      "แตกปัญหาใหญ่เป็นขั้นเล็กก่อนเขียนโค้ด",
    ],
    stack: ["C++", "Algorithm", "Problem Solving"],
    loot: "ไม่ได้ไปค่าย 2 แต่ได้วิธีคิดเป็นขั้นตอนที่ใช้ต่อทุกโปรเจกต์",
    note: "ได้ C++ กับเพื่อนสายคอมกลับบ้าน ถือว่ากำไร",
    gallery: [
      { src: "assets/posn-photo.webp", cap: "รับเกียรติบัตรค่าย 1" },
      { src: "assets/posn-cert.webp", cap: "เกียรติบัตร" },
    ],
  },
  {
    id: "rov",
    date: "ม.ค. 2568", year: "2025",
    title: "depa E-Sports In Schools",
    event: "การแข่งขัน E-Sports เกม ROV",
    result: "*รองชนะเลิศอันดับ 2* · เงินรางวัล 2,000 บาท",
    rarity: "epic",
    level: "ระดับโรงเรียน",
    role: "ผู้เล่น · IGN สกิบิดี้บิดี้บิดู้",
    cover: "assets/rov-1.webp",
    summary: "เล่น ROV กับเพื่อนมาตลอด เลยลองลงแข่ง ได้รองชนะเลิศอันดับ 2",
    brief: [
      "วางแผน วิเคราะห์คู่แข่ง และตัดสินใจร่วมกันในเกมที่เปลี่ยนเร็ว",
    ],
    did: [
      "สื่อสารกับทีมระหว่างเกม",
      "วิเคราะห์คู่แข่ง และปรับแผนตามเกม",
    ],
    stack: ["Teamwork", "Shotcalling", "Decision Making"],
    loot: "ฝีมือแต่ละคนเก่งสุดเมื่อทุกคนรู้บทบาทและเล่นเป็นทีม",
    note: "ชื่อในเกมไม่จริงจัง แต่เรื่องทีมจริงจังนะ",
    gallery: [
      { src: "assets/rov-1.webp", cap: "ทีมรับรางวัล" },
      { src: "assets/rov-2.webp", cap: "บนเวที" },
      { src: "assets/g-rov.webp", cap: "โปรไฟล์ ROV" },
    ],
  },
];
